name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  DOCKER_IMAGE_TAG: "jamesits/meshcentral2:latest"

trigger:
  batch: true
  branches:
    include: [ "master" ]
  paths:
    include: [ "*" ]
    exclude: [ "README.md" ]

jobs:
  # different variants
  - job: docker
    displayName: "docker build"
    pool:
      vmImage: "ubuntu-latest"
    workspace:
      clean: all
    timeoutInMinutes: 20

    steps:
    - checkout: self
      clean: true
      submodules: true

    - bash: |
        set -Eeuo pipefail
        docker build -t "$(DOCKER_IMAGE_TAG)" .
        docker images --digests "$(DOCKER_IMAGE_TAG)"
      displayName: "Build image"

    - task: Docker@1
      displayName: "Docker login"
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: "Docker Hub: Jamesits"
        command: login

    - bash: |
        set -Eeuo pipefail
        docker push "$(DOCKER_IMAGE_TAG)"
      displayName: "Push image"
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))

    - task: Docker@1
      displayName: "Docker logout"
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: "Docker Hub: Jamesits"
        command: logout
