services:
  meshcentral2:
    image: "docker.io/jamesits/meshcentral2:latest"
    restart: "unless-stopped"
    ulimits:
      nofile:
        soft: 800000
        hard: 1000000
    volumes:
      - "./deployment/meshcentral-data:/srv/meshcentral2/meshcentral-data"
      - "./deployment/meshcentral-files:/srv/meshcentral2/meshcentral-files"
      - "./deployment/meshcentral-backup:/srv/meshcentral2/backup"
    env_file:
      - "./deployment/meshcentral.env"
    ports:
      - "80:80"
      - "443:443"
      - "4433:4433"

  mongo:
    image: "docker.io/library/mongo:8"
    restart: "unless-stopped"
    volumes:
      - "./deployment/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./deployment/mongodb-data:/data/db"
      - "./deployment/mongodb-config:/data/configdb"
    env_file:
      - "./deployment/mongodb.env"
